version: '3'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_app_backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: todo_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_app_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: